### ISSUE TITLE
Key is not working (No error)

### ISSUE THREAD

**Issue by MrCerise** [Agent-Squad-Productions/extramenu#4] opened 2023-09-01 18:06 UTC
**Describe the bug**
The menu key is not working

**To Reproduce**
1. Click on 'M'

**Expected behavior**
Open the Menu
**Desktop (please complete the following information):**
- Windows

**Comment by AgentBUB** [comment] 2023-10-07 18:41
Sorry for the delayed reply, but could you please provide errors from the console to assist us in sorting out a solution.

**Comment by AgentBUB** [comment] 2023-10-07 18:58
So, I just tested and am having no issues. I would ensure you have the correct NativeUI installed and updated menu. Also, ensure no other scripts or menus used in your server are assigned to the M key.

**Comment by AgentBUB** [comment] 2023-10-11 00:30
@MrCerise if you could please confirm if you are still experiencing any errors, that would be appreciated.

**Comment by MrCerise** [comment] 2023-10-11 05:45
It was still an error

**Comment by MrCerise** [comment] 2023-10-11 05:46
My question is can you do a tutorial to know how to install the script
please ?

**Comment by AgentBUB** [comment] 2023-10-11 05:53
There is a tutorial for the entire script. You can find it on the [Github wiki](https://github.com/Shadow-Develops/extramenu/wiki) or our official [documentation website](https://docs.shadowdevs.com).

**Comment by MrCerise** [comment] 2023-10-11 05:56
And can you give the NativeUI direct download link please ?

**Comment by AgentBUB** [comment] 2023-10-11 05:58
You can find it on [their FiveM Forum post](https://forum.cfx.re/t/release-dev-nativeuilua/98318) or [their Github](https://github.com/FrazzIe/NativeUILua/releases/tag/2.1.0).

**Comment by MrCerise** [comment] 2023-10-11 05:59
Ho, yeah, I remember the error now...
The menu wouldn't whant to came with the key pressed

**Comment by AgentBUB** [comment] 2023-10-11 06:02
Are you trying to say the menu wouldn't open when you pressed the key?
If so, make sure the following are true:
- You are in a vehicle.
- NativeUI was correctly started. (It comes with an example and the actual script in the download, so install the script not the example.)
- You do not have permissions or other opening methods enabled.

If it still doesn't work, there should be an error for why either in your F8 or server console.

**Comment by MrCerise** [comment] 2023-10-11 06:04
No error on the console and when I was doing the command in the chat, it's
was working

**Comment by AgentBUB** [comment] 2023-10-11 06:05
Well, you have to enable the command as it is disabled by default. And if there is no error, the issue is likely on your client or server's end as the script would provide an error if it was not opening due to a script error.

**Comment by MrCerise** [comment] 2023-10-11 10:41
I mean, the command work but not the key

**Comment by AgentBUB** [comment] 2023-10-15 00:58
Well did you set it to be command open only, as that is an option?

**Comment by AgentBUB** [comment] 2023-11-25 00:10
I will go ahead and close this now due to inactivity. If you are still having issues, please create a new issue with more details/error logs or open a support ticket in our [Discord](https://discord.gg/shadowdevs).

**Closed as completed by AgentBUB** 2023-11-25 00:10 UTC
Labels: question
